<?php

/**
 * @file
 * Hooks.
 */

/**
 * Implements hook_help().
 */
function waterwheel_help($path, $arg) {
  switch ($path) {
    case 'admin/help#waterwheel':
      return t('<p>Integrates with the Waterwheel-js libriary</p>');
      break;
  }
}

/**
 * Implements hook_theme().
 */
function waterwheel_theme() {
  return array(
    'swagger_ui' => array(
      'render element' => 'elements',
    ),
  );
}
